package com.example.customexoplayer.components.utils

object Constants {
    const val HEIGHT_VIDEO_SELECTED = "HEIGHT_VIDEO_SELECTED"
    const val WIDTH_VIDEO_SELECTED = "WIDTH_VIDEO_SELECTED"
    const val BITRATE_VIDEO_SELECTED = "BITRATE_VIDEO_SELECTED"
    const val LANGUAGE_VIDEO_SELECTED = "LANGUAGE_VIDEO_SELECTED"
    const val PLAYBACK_SPEED_VIDEO_SELECTED = "PLAYBACK_SPEED_VIDEO_SELECTED"

    const val EXO_PLAYER_RESOURCE = "EXO_PLAYER_RESOURCE"
    const val EXO_TRACK_INDEX = "EXO_TRACK_INDEX"
}